---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-vm
spec:
  certificateOwnerRef: false
  dnsNames:
    - pr-placeholder.demo.q3dm17.ru
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: demo-vm-tls
