---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: demo-vm
  labels:
    pr: placeholder
spec:
  virtualMachineClassName: generic
  runPolicy: AlwaysOn
  cpu:
    cores: 1
    coreFraction: 50%
  memory:
    size: 1Gi
  disruptions:
    restartApprovalMode: Automatic
  provisioning:
    type: UserData
    userData: |
      #cloud-config
  blockDeviceRefs:
    - kind: VirtualDisk
      name: root-disk
