---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: ClusterVirtualImage
metadata:
  name: dvp-demo-argo-image
spec:
  dataSource:
    type: HTTP
    http:
      url: https://mirror.yandex.ru/ubuntu-cloud-images/noble/20260323/noble-server-cloudimg-amd64.img
